eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

my.val: ${random.value}
my.number: ${random.int}