eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId: instanceId: ${vcap.application.instance_id:${spring.application.name}:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/